/**
 * activities module
 * SQL updates
 *
 * Part of »Zugzwang Project«
 * https://www.zugzwang.org/modules/activities
 *
 * @author Gustaf Mossakowski <gustaf@koenige.org>
 * @copyright Copyright © 2020-2022 Gustaf Mossakowski
 * @license http://opensource.org/licenses/lgpl-3.0.html LGPL-3.0
 */

/* 2020-09-10-1 */	ALTER TABLE `usergroups` CHANGE `usergroup` `usergroup` varchar(80) COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `usergroup_id`;
/* 2020-11-30-2 */	ALTER TABLE `activities` CHANGE `activity_uri` `activity_uri` varchar(255) COLLATE 'latin1_general_ci' NOT NULL AFTER `activity_ip`;
/* 2020-11-30-3 */	ALTER TABLE `activities` ADD UNIQUE `participation_id_activity_category_id_activity_date_activity_uri` (`participation_id`, `activity_category_id`, `activity_date`, `activity_uri`), DROP INDEX `participation_id_activity_category_id_activity_date`;
/* 2021-02-23-1 */	CREATE TABLE `contacts_access` (`contact_access_id` int unsigned NOT NULL AUTO_INCREMENT, `contact_id` int unsigned DEFAULT NULL, `usergroup_id` int unsigned NOT NULL, `access_category_id` int unsigned NOT NULL, `property_category_id` int unsigned NOT NULL, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`contact_access_id`), UNIQUE KEY `contact_id_usergroup_id_property_category_id` (`contact_id`,`usergroup_id`,`property_category_id`), KEY `usergroup_id` (`usergroup_id`), KEY `access_category_id` (`access_category_id`), KEY `property_category_id` (`property_category_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-02-23-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'contact_id', 'no-delete');
/* 2021-02-23-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups', 'usergroup_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'usergroup_id', 'no-delete');
/* 2021-02-23-4 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'access_category_id', 'no-delete');
/* 2021-02-23-5 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'property_category_id', 'no-delete');
/* 2021-03-14-1 */	ALTER TABLE `participations` ADD `sequence` smallint unsigned NULL AFTER `status_category_id`;
/* 2021-03-14-2 */	ALTER TABLE `participations` ADD `role` varchar(255) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `status_category_id`;
/* 2021-06-25-1 */	CREATE TABLE `access` (`access_id` int unsigned NOT NULL AUTO_INCREMENT, `access_key` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `explanation` text COLLATE utf8mb4_unicode_ci, PRIMARY KEY (`access_id`), UNIQUE KEY `access_key` (`access_key`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-06-25-2 */	CREATE TABLE `access_usergroups` (`access_usergroup_id` int unsigned NOT NULL AUTO_INCREMENT, `access_id` int unsigned NOT NULL, `usergroup_id` int unsigned NOT NULL, `restricted_to_field` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL, PRIMARY KEY (`access_usergroup_id`), UNIQUE KEY `access_id_usergroup_id` (`access_id`,`usergroup_id`), KEY `usergroup_id` (`usergroup_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-06-25-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'access', 'access_id', (SELECT DATABASE()), 'access_usergroups', 'access_usergroup_id', 'access_id', 'delete');
/* 2021-06-25-4 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups', 'usergroup_id', (SELECT DATABASE()), 'access_usergroups', 'access_usergroup_id', 'usergroup_id', 'no-delete');
/* 2021-07-22-1 */	CREATE TABLE `forms` (`form_id` int unsigned NOT NULL AUTO_INCREMENT, `event_id` int unsigned DEFAULT NULL, `access` enum('public','login') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'public', `created` datetime NOT NULL, `header` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `lead` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `footer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `authentication_mail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `confirmation_mail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `form_category_id` int unsigned DEFAULT NULL, `address` enum('formal','informal') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'formal', PRIMARY KEY (`form_id`), UNIQUE KEY `event_id` (`event_id`), KEY `form_category_id` (`form_category_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'forms', 'form_id', 'event_id', 'delete');
/* 2021-07-22-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'forms', 'form_id', 'form_category_id', 'no-delete');
/* 2021-07-22-4 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Forms', NULL, NULL, 'forms', NULL, NULL, NOW());
/* 2021-07-22-5 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Registration', NULL, (SELECT category_id FROM categories c WHERE path = 'forms'), 'forms/registration', NULL, 1, NOW());
/* 2021-07-22-6 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Application', NULL, (SELECT category_id FROM categories c WHERE path = 'forms'), 'forms/application', NULL, 2, NOW());
/* 2021-07-22-7 */	CREATE TABLE `formfields` (`formfield_id` int unsigned NOT NULL AUTO_INCREMENT, `form_id` int unsigned NOT NULL, `formfield` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `explanation` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `formfield_category_id` int unsigned NOT NULL, `area` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `sequence` tinyint unsigned NOT NULL, `parameters` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `edit_from` datetime DEFAULT NULL, `edit_by` datetime DEFAULT NULL, `main_formfield_id` int unsigned DEFAULT NULL, PRIMARY KEY (`formfield_id`), KEY `form_id` (`form_id`), KEY `formfield_category_id` (`formfield_category_id`), KEY `main_formfield_id` (`main_formfield_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-8 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'forms', 'form_id', (SELECT DATABASE()), 'formfields', 'formfield_id', 'form_id', 'delete');
/* 2021-07-22-9 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'formfields', 'formfield_id', 'formfield_category_id', 'delete');
/* 2021-07-22-10 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'formfields', 'formfield_id', (SELECT DATABASE()), 'formfields', 'formfield_id', 'main_formfield_id', 'delete');
/* 2021-07-22-11 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Field Types', NULL, NULL, 'field-types', NULL, NULL, NOW());
/* 2021-07-22-12 */	CREATE TABLE `registrations` (`registration_id` int unsigned NOT NULL AUTO_INCREMENT, `usergroup_id` int unsigned NOT NULL, `event_id` int unsigned DEFAULT NULL, `organisation_contact_id` int unsigned DEFAULT NULL, `min_participants` smallint unsigned DEFAULT NULL, `max_participants` smallint unsigned DEFAULT NULL, `waiting_participants` smallint unsigned DEFAULT NULL, `show_remaining_from` smallint unsigned DEFAULT NULL, `registration_hash` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `parameters` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`registration_id`), UNIQUE KEY `usergroup_id` (`usergroup_id`,`event_id`), KEY `event_id` (`event_id`), KEY `contact_id` (`organisation_contact_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-13 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups', 'usergroup_id', (SELECT DATABASE()), 'registrations', 'registration_id', 'usergroup_id', 'no-delete');
/* 2021-07-22-14 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'registrations', 'registration_id', 'event_id', 'delete');
/* 2021-07-22-15 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'registrations', 'registration_id', 'organisation_contact_id', 'no-delete');
/* 2021-07-22-16 */	CREATE TABLE `registrationtexts` (`registrationtext_id` int unsigned NOT NULL AUTO_INCREMENT, `contact_id` int unsigned NOT NULL, `formfield_id` int unsigned NOT NULL, `registrationtext` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`registrationtext_id`), UNIQUE KEY `contact_id` (`contact_id`,`formfield_id`), KEY `formfield_id` (`formfield_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-17 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'registrationtexts', 'registrationtext_id', 'contact_id', 'no-delete');
/* 2021-07-22-18 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'formfields', 'formfield_id', (SELECT DATABASE()), 'registrationtexts', 'registrationtext_id', 'formfield_id', 'no-delete');
/* 2021-07-22-19 */	CREATE TABLE `registrationvarchars` (`registrationvarchar_id` int unsigned NOT NULL AUTO_INCREMENT, `contact_id` int unsigned NOT NULL, `formfield_id` int unsigned NOT NULL, `registrationvarchar` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`registrationvarchar_id`), UNIQUE KEY `contact_id` (`contact_id`,`formfield_id`), KEY `formfield_id` (`formfield_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-20 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'registrationvarchars', 'registrationvarchar_id', 'contact_id', 'no-delete');
/* 2021-07-22-21 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'formfields', 'formfield_id', (SELECT DATABASE()), 'registrationvarchars', 'registrationvarchar_id', 'formfield_id', 'no-delete');
/* 2021-07-22-22 */	ALTER TABLE `participations` ADD `event_id` int unsigned NULL AFTER `usergroup_id`;
/* 2021-07-22-23 */	ALTER TABLE `participations` ADD INDEX `contact_id_usergroup_id_date_begin_event_id` (`contact_id`, `usergroup_id`, `date_begin`, `event_id`), ADD INDEX `event_id` (`event_id`), DROP INDEX `contact_id`;
/* 2021-07-22-24 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'participations', 'participation_id', 'event_id', 'no-delete');
/* 2021-10-05-1 */	ALTER TABLE `activities` ADD `comment` varchar(255) COLLATE 'latin1_general_ci' NULL;
/* 2021-10-05-2 */	ALTER TABLE `activities` CHANGE `comment` `comment` varchar(255) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `activity_uri`;
/* 2022-02-22-1 */	ALTER TABLE `access` CHANGE `access_key` `access_key` varchar(32) COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `access_id`, ADD `module` text(16) COLLATE 'utf8mb4_unicode_ci' NULL;
/* 2022-04-17-1 */	ALTER TABLE `forms` CHANGE `event_id` `event_id` int unsigned NOT NULL AFTER `form_id`;
/* 2022-04-17-2 */	ALTER TABLE `usergroups` CHANGE `identifier` `identifier` varchar(32) COLLATE 'latin1_general_ci' NOT NULL AFTER `usergroup`, CHANGE `active` `active` enum('yes','no') COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'yes' AFTER `sequence`;
/* 2022-04-17-3 */	ALTER TABLE `usergroups` CHANGE `last_update` `last_update` timestamp NOT NULL AFTER `parameters`;
/* 2022-04-18-1 */	ALTER TABLE `forms` CHANGE `access` `access` enum('public','login') COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'public' AFTER `event_id`, CHANGE `address` `address` enum('formal','informal') COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'formal' AFTER `form_category_id`;
/* 2022-04-18-2 */	ALTER TABLE `forms` CHANGE `created` `created` datetime NOT NULL AFTER `address`;
