/**
 * activities module
 * SQL updates
 *
 * Part of »Zugzwang Project«
 * https://www.zugzwang.org/modules/activities
 *
 * @author Gustaf Mossakowski <gustaf@koenige.org>
 * @copyright Copyright © 2020-2023 Gustaf Mossakowski
 * @license http://opensource.org/licenses/lgpl-3.0.html LGPL-3.0
 */

/* 2020-09-10-1 */	ALTER TABLE `usergroups` CHANGE `usergroup` `usergroup` varchar(80) COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `usergroup_id`;
/* 2020-11-30-2 */	ALTER TABLE `activities` CHANGE `activity_uri` `activity_uri` varchar(255) COLLATE 'latin1_general_ci' NOT NULL AFTER `activity_ip`;
/* 2020-11-30-3 */	ALTER TABLE `activities` ADD UNIQUE `participation_id_activity_category_id_activity_date_activity_uri` (`participation_id`, `activity_category_id`, `activity_date`, `activity_uri`), DROP INDEX `participation_id_activity_category_id_activity_date`;
/* 2021-02-23-1 */	CREATE TABLE `contacts_access` (`contact_access_id` int unsigned NOT NULL AUTO_INCREMENT, `contact_id` int unsigned DEFAULT NULL, `usergroup_id` int unsigned NOT NULL, `access_category_id` int unsigned NOT NULL, `property_category_id` int unsigned NOT NULL, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`contact_access_id`), UNIQUE KEY `contact_id_usergroup_id_property_category_id` (`contact_id`,`usergroup_id`,`property_category_id`), KEY `usergroup_id` (`usergroup_id`), KEY `access_category_id` (`access_category_id`), KEY `property_category_id` (`property_category_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-02-23-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'contact_id', 'no-delete');
/* 2021-02-23-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups', 'usergroup_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'usergroup_id', 'no-delete');
/* 2021-02-23-4 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'access_category_id', 'no-delete');
/* 2021-02-23-5 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'contacts_access', 'contact_access_id', 'property_category_id', 'no-delete');
/* 2021-03-14-1 */	ALTER TABLE `participations` ADD `sequence` smallint unsigned NULL AFTER `status_category_id`;
/* 2021-03-14-2 */	ALTER TABLE `participations` ADD `role` varchar(255) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `status_category_id`;
/* 2021-06-25-1 */	CREATE TABLE `access` (`access_id` int unsigned NOT NULL AUTO_INCREMENT, `access_key` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `explanation` text COLLATE utf8mb4_unicode_ci, PRIMARY KEY (`access_id`), UNIQUE KEY `access_key` (`access_key`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-06-25-2 */	CREATE TABLE `access_usergroups` (`access_usergroup_id` int unsigned NOT NULL AUTO_INCREMENT, `access_id` int unsigned NOT NULL, `usergroup_id` int unsigned NOT NULL, `restricted_to_field` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL, PRIMARY KEY (`access_usergroup_id`), UNIQUE KEY `access_id_usergroup_id` (`access_id`,`usergroup_id`), KEY `usergroup_id` (`usergroup_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-06-25-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'access', 'access_id', (SELECT DATABASE()), 'access_usergroups', 'access_usergroup_id', 'access_id', 'delete');
/* 2021-06-25-4 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups', 'usergroup_id', (SELECT DATABASE()), 'access_usergroups', 'access_usergroup_id', 'usergroup_id', 'no-delete');
/* 2021-07-22-1 */	CREATE TABLE `forms` (`form_id` int unsigned NOT NULL AUTO_INCREMENT, `event_id` int unsigned DEFAULT NULL, `access` enum('public','login') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'public', `created` datetime NOT NULL, `header` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `lead` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `footer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `authentication_mail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `confirmation_mail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `form_category_id` int unsigned DEFAULT NULL, `address` enum('formal','informal') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'formal', PRIMARY KEY (`form_id`), UNIQUE KEY `event_id` (`event_id`), KEY `form_category_id` (`form_category_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'forms', 'form_id', 'event_id', 'delete');
/* 2021-07-22-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'forms', 'form_id', 'form_category_id', 'no-delete');
/* 2021-07-22-4 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Forms', NULL, NULL, 'forms', NULL, NULL, NOW());
/* 2021-07-22-5 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Registration', NULL, (SELECT category_id FROM categories c WHERE path = 'forms'), 'forms/registration', NULL, 1, NOW());
/* 2021-07-22-6 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Application', NULL, (SELECT category_id FROM categories c WHERE path = 'forms'), 'forms/application', NULL, 2, NOW());
/* 2021-07-22-7 */	CREATE TABLE `formfields` (`formfield_id` int unsigned NOT NULL AUTO_INCREMENT, `form_id` int unsigned NOT NULL, `formfield` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `explanation` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `formfield_category_id` int unsigned NOT NULL, `area` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `sequence` tinyint unsigned NOT NULL, `parameters` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `edit_from` datetime DEFAULT NULL, `edit_by` datetime DEFAULT NULL, `main_formfield_id` int unsigned DEFAULT NULL, PRIMARY KEY (`formfield_id`), KEY `form_id` (`form_id`), KEY `formfield_category_id` (`formfield_category_id`), KEY `main_formfield_id` (`main_formfield_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-8 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'forms', 'form_id', (SELECT DATABASE()), 'formfields', 'formfield_id', 'form_id', 'delete');
/* 2021-07-22-9 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'formfields', 'formfield_id', 'formfield_category_id', 'delete');
/* 2021-07-22-10 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'formfields', 'formfield_id', (SELECT DATABASE()), 'formfields', 'formfield_id', 'main_formfield_id', 'delete');
/* 2021-07-22-11 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Field Types', NULL, NULL, 'field-types', NULL, NULL, NOW());
/* 2021-07-22-12 */	CREATE TABLE `registrations` (`registration_id` int unsigned NOT NULL AUTO_INCREMENT, `usergroup_id` int unsigned NOT NULL, `event_id` int unsigned DEFAULT NULL, `organisation_contact_id` int unsigned DEFAULT NULL, `min_participants` smallint unsigned DEFAULT NULL, `max_participants` smallint unsigned DEFAULT NULL, `waiting_participants` smallint unsigned DEFAULT NULL, `show_remaining_from` smallint unsigned DEFAULT NULL, `registration_hash` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `parameters` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`registration_id`), UNIQUE KEY `usergroup_id` (`usergroup_id`,`event_id`), KEY `event_id` (`event_id`), KEY `contact_id` (`organisation_contact_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-13 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups', 'usergroup_id', (SELECT DATABASE()), 'registrations', 'registration_id', 'usergroup_id', 'no-delete');
/* 2021-07-22-14 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'registrations', 'registration_id', 'event_id', 'delete');
/* 2021-07-22-15 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'registrations', 'registration_id', 'organisation_contact_id', 'no-delete');
/* 2021-07-22-16 */	CREATE TABLE `registrationtexts` (`registrationtext_id` int unsigned NOT NULL AUTO_INCREMENT, `contact_id` int unsigned NOT NULL, `formfield_id` int unsigned NOT NULL, `registrationtext` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`registrationtext_id`), UNIQUE KEY `contact_id` (`contact_id`,`formfield_id`), KEY `formfield_id` (`formfield_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-17 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'registrationtexts', 'registrationtext_id', 'contact_id', 'no-delete');
/* 2021-07-22-18 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'formfields', 'formfield_id', (SELECT DATABASE()), 'registrationtexts', 'registrationtext_id', 'formfield_id', 'no-delete');
/* 2021-07-22-19 */	CREATE TABLE `registrationvarchars` (`registrationvarchar_id` int unsigned NOT NULL AUTO_INCREMENT, `contact_id` int unsigned NOT NULL, `formfield_id` int unsigned NOT NULL, `registrationvarchar` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`registrationvarchar_id`), UNIQUE KEY `contact_id` (`contact_id`,`formfield_id`), KEY `formfield_id` (`formfield_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2021-07-22-20 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'registrationvarchars', 'registrationvarchar_id', 'contact_id', 'no-delete');
/* 2021-07-22-21 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'formfields', 'formfield_id', (SELECT DATABASE()), 'registrationvarchars', 'registrationvarchar_id', 'formfield_id', 'no-delete');
/* 2021-07-22-22 */	ALTER TABLE `participations` ADD `event_id` int unsigned NULL AFTER `usergroup_id`;
/* 2021-07-22-23 */	ALTER TABLE `participations` ADD INDEX `contact_id_usergroup_id_date_begin_event_id` (`contact_id`, `usergroup_id`, `date_begin`, `event_id`), ADD INDEX `event_id` (`event_id`), DROP INDEX `contact_id`;
/* 2021-07-22-24 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'participations', 'participation_id', 'event_id', 'no-delete');
/* 2021-10-05-1 */	ALTER TABLE `activities` ADD `comment` varchar(255) COLLATE 'latin1_general_ci' NULL;
/* 2021-10-05-2 */	ALTER TABLE `activities` CHANGE `comment` `comment` varchar(255) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `activity_uri`;
/* 2022-02-22-1 */	ALTER TABLE `access` CHANGE `access_key` `access_key` varchar(32) COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `access_id`, ADD `module` text(16) COLLATE 'utf8mb4_unicode_ci' NULL;
/* 2022-04-17-1 */	ALTER TABLE `forms` CHANGE `event_id` `event_id` int unsigned NOT NULL AFTER `form_id`;
/* 2022-04-17-2 */	ALTER TABLE `usergroups` CHANGE `identifier` `identifier` varchar(32) COLLATE 'latin1_general_ci' NOT NULL AFTER `usergroup`, CHANGE `active` `active` enum('yes','no') COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'yes' AFTER `sequence`;
/* 2022-04-17-3 */	ALTER TABLE `usergroups` CHANGE `last_update` `last_update` timestamp NOT NULL AFTER `parameters`;
/* 2022-04-18-1 */	ALTER TABLE `forms` CHANGE `access` `access` enum('public','login') COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'public' AFTER `event_id`, CHANGE `address` `address` enum('formal','informal') COLLATE 'latin1_general_ci' NOT NULL DEFAULT 'formal' AFTER `form_category_id`;
/* 2022-04-18-2 */	ALTER TABLE `forms` CHANGE `created` `created` datetime NOT NULL AFTER `address`;
/* 2022-10-07-1 */	CREATE TABLE `participations_contacts` (`participation_contact_id` int unsigned NOT NULL AUTO_INCREMENT, `participation_id` int unsigned NOT NULL, `contact_id` int unsigned NOT NULL, PRIMARY KEY (`participation_contact_id`), UNIQUE KEY `participation_id_contact_id` (`participation_id`,`contact_id`), KEY `contact_id` (`contact_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2022-10-07-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'participations', 'participation_id', (SELECT DATABASE()), 'participations_contacts', 'participation_contact_id', 'participation_id', 'no-delete');
/* 2022-10-07-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'participations_contacts', 'participation_contact_id', 'contact_id', 'no-delete');
/* 2022-10-07-4 */	CREATE TABLE `participations_websites` ( `participation_website_id` int unsigned NOT NULL AUTO_INCREMENT, `participation_id` int unsigned NOT NULL, `website_id` int unsigned NOT NULL, PRIMARY KEY (`participation_website_id`), UNIQUE KEY `participation_id_website_id` (`participation_id`,`website_id`), KEY `website_id` (`website_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2022-10-07-5 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'participations', 'participation_id', (SELECT DATABASE()), 'participations_websites', 'participation_website_id', 'participation_id', 'no-delete');
/* 2022-10-07-6 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), 'participations_websites', 'participation_website_id', 'website_id', 'no-delete');
/* 2022-10-13-1 */	ALTER TABLE `formfields` CHANGE `parameters` `parameters` varchar(1250) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `sequence`;
/* 2023-01-09-1 */	ALTER TABLE `access` CHANGE `access_key` `access_key` varchar(48) COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `access_id`;
/* 2023-01-18-1 */	CREATE TABLE `mailings` (`mailing_id` int unsigned NOT NULL AUTO_INCREMENT, `event_id` int unsigned NOT NULL, `subject` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `sender_contact_id` int unsigned NOT NULL, `sender_mail` varchar(127) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL, `sent` datetime DEFAULT NULL, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`mailing_id`), KEY `event_id` (`event_id`), KEY `sender_contact_id` (`sender_contact_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2023-01-18-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'mailings', 'mailing_id', 'event_id', 'no-delete');
/* 2023-01-18-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'mailings', 'mailing_id', 'sender_contact_id', 'no-delete');
/* 2023-01-18-4 */	CREATE TABLE `mailings_contacts` (`mailing_contact_id` int unsigned NOT NULL AUTO_INCREMENT, `mailing_id` int unsigned NOT NULL, `recipient_contact_id` int unsigned NOT NULL, `recipient_mail` varchar(127) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`mailing_contact_id`), UNIQUE KEY `mailing_id_recipient_contact_id` (`mailing_id`,`recipient_contact_id`), KEY `recipient_contact_id` (`recipient_contact_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2023-01-18-5 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'mailings', 'mailing_id', (SELECT DATABASE()), 'mailings_contacts', 'mailing_contact_id', 'mailing_id', 'delete');
/* 2023-01-18-6 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'mailings_contacts', 'mailing_contact_id', 'recipient_contact_id', 'delete');
/* 2023-01-30-1 */	CREATE TABLE `usergroups_categories` (`uc_id` int unsigned NOT NULL AUTO_INCREMENT, `usergroup_id` int unsigned NOT NULL, `category_id` int unsigned NOT NULL, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`uc_id`), UNIQUE KEY `usergroup_id` (`usergroup_id`,`category_id`), KEY `category_id` (`category_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2023-01-30-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups_categories', 'uc_id', (SELECT DATABASE()), 'usergroups', 'usergroup_id', 'usergroup_id', 'delete');
/* 2023-01-30-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'usergroups_categories', 'uc_id', (SELECT DATABASE()), 'categories', 'category_id', 'category_id', 'no-delete');
/* 2023-01-31-1 */	CREATE TABLE `formtemplates` (`formtemplate_id` int unsigned NOT NULL AUTO_INCREMENT, `form_id` int unsigned NOT NULL, `template` text COLLATE utf8mb4_unicode_ci NOT NULL, `template_category_id` int unsigned NOT NULL, `formfield_id` int unsigned DEFAULT NULL, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`formtemplate_id`), UNIQUE KEY `form_id_template_category_id_formfield_id` (`form_id`,`template_category_id`,`formfield_id`), KEY `template_category_id` (`template_category_id`), KEY `formfield_id` (`formfield_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2023-01-31-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'forms', 'form_id', (SELECT DATABASE()), 'formtemplates', 'formtemplate_id', 'form_id', 'delete');
/* 2023-01-31-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'formtemplates', 'formtemplate_id', 'template_category_id', 'no-delete');
/* 2023-01-31-4 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'formfields', 'formfield_id', (SELECT DATABASE()), 'formtemplates', 'formtemplate_id', 'formfield_id', 'delete');
/* 2023-01-31-5 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Template Types', NULL, NULL, 'template-types', NULL, NULL, NOW());
/* 2023-01-31-6 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Authentication Mail', 'First mail sent out to check the applicant’s mail address.', (SELECT category_id FROM categories c WHERE path = 'template-types'), 'template-types/authentication', '&alias=template-types/authentication', 1, NOW());
/* 2023-01-31-7 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Confirmation Mail', 'Second mail sent out to confirm the application.', (SELECT category_id FROM categories c WHERE path = 'template-types'), 'template-types/confirmation', '&alias=template-types/confirmation', 2, NOW());
/* 2023-01-31-8 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Field changed Mail', 'Mail to send if a field value was added or changed.', (SELECT category_id FROM categories c WHERE path = 'template-types'), 'template-types/field-changed', '&alias=template-types/field-changed&formfield=1', 3, NOW());
/* 2023-02-09-1 */	INSERT INTO formtemplates (form_id, template, template_category_id) SELECT form_id, authentication_mail, (SELECT category_id FROM categories c WHERE path = 'template-types/authentication' OR parameters LIKE '%&alias=template-types/authentication%') FROM forms WHERE NOT ISNULL(authentication_mail);
/* 2023-02-09-2 */	INSERT INTO formtemplates (form_id, template, template_category_id) SELECT form_id, confirmation_mail, (SELECT category_id FROM categories c WHERE path = 'template-types/confirmation' OR parameters LIKE '%&alias=template-types/confirmation%') FROM forms WHERE NOT ISNULL(confirmation_mail);
/* 2023-02-09-3 */	INSERT INTO _translationfields (db_name, table_name, field_name, field_type) SELECT DATABASE(), 'formtemplates', 'template', 'text' FROM _translationfields WHERE table_name = 'forms' AND field_name = 'authentication_mail';
/* 2023-02-09-4 */	UPDATE _translations_text LEFT JOIN _translationfields USING (translationfield_id) LEFT JOIN forms ON forms.form_id = _translations_text.field_id SET translationfield_id = (SELECT translationfield_id FROM _translationfields t2 WHERE db_name = (SELECT DATABASE()) AND table_name = 'formtemplates' AND field_name = 'template' AND field_type = 'text'), field_id = (SELECT formtemplate_id FROM formtemplates WHERE form_id = _translations_text.field_id AND template_category_id = (SELECT category_id FROM categories c WHERE path = 'template-types/authentication' OR parameters LIKE '%&alias=template-types/authentication%')) WHERE db_name = (SELECT DATABASE()) AND table_name = 'forms' AND field_name = 'authentication_mail' AND field_type = 'text' AND NOT ISNULL(form_id);
/* 2023-02-09-5 */	UPDATE _translations_text LEFT JOIN _translationfields USING (translationfield_id) LEFT JOIN forms ON forms.form_id = _translations_text.field_id SET translationfield_id = (SELECT translationfield_id FROM _translationfields t2 WHERE db_name = (SELECT DATABASE()) AND table_name = 'formtemplates' AND field_name = 'template' AND field_type = 'text'), field_id = (SELECT formtemplate_id FROM formtemplates WHERE form_id = _translations_text.field_id AND template_category_id = (SELECT category_id FROM categories c WHERE path = 'template-types/confirmation' OR parameters LIKE '%&alias=template-types/confirmation%')) WHERE db_name = (SELECT DATABASE()) AND table_name = 'forms' AND field_name = 'confirmation_mail' AND field_type = 'text' AND NOT ISNULL(form_id);
/* 2023-02-09-6 */	DELETE FROM _translations_text WHERE translationfield_id = (SELECT translationfield_id FROM _translationfields WHERE db_name = (SELECT DATABASE()) AND table_name = 'forms' AND field_name = 'authentication_mail' AND field_type = 'text');
/* 2023-02-09-7 */	DELETE FROM _translations_text WHERE translationfield_id = (SELECT translationfield_id FROM _translationfields WHERE db_name = (SELECT DATABASE()) AND table_name = 'forms' AND field_name = 'confirmation_mail' AND field_type = 'text');
/* 2023-02-09-8 */	DELETE FROM _translationfields WHERE db_name = (SELECT DATABASE()) AND table_name = 'forms' AND field_name = 'authentication_mail' AND field_type = 'text';
/* 2023-02-09-9 */	DELETE FROM _translationfields WHERE db_name = (SELECT DATABASE()) AND table_name = 'forms' AND field_name = 'confirmation_mail' AND field_type = 'text';
/* 2023-02-09-10 */	ALTER TABLE `forms` DROP `authentication_mail`, DROP `confirmation_mail`;
/* 2023-02-09-11 */	UPDATE _relations SET `delete` = 'no-delete' WHERE `master_db` = (SELECT DATABASE()) AND `master_table` = 'categories' AND `master_field` = 'category_id' AND `detail_db` = (SELECT DATABASE()) AND `detail_table` = 'formfields' AND `detail_id_field` = 'formfield_id' AND `detail_field` = 'formfield_category_id';
/* 2023-02-16-1 */	CREATE TABLE `formtemplates_defaults` (`formtemplate_default_id` int unsigned NOT NULL AUTO_INCREMENT, `template_default` text COLLATE utf8mb4_unicode_ci NOT NULL, `template_category_id` int unsigned NOT NULL, `language_id` int unsigned NOT NULL, `form_category_id` int unsigned NOT NULL, `org_contact_id` int unsigned DEFAULT NULL, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`formtemplate_default_id`), UNIQUE KEY `language_id` (`language_id`,`template_category_id`,`form_category_id`,`org_contact_id`), KEY `template_category_id` (`template_category_id`), KEY `form_category_id` (`form_category_id`), KEY `org_contact_id` (`org_contact_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2023-02-16-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'formtemplates_defaults', 'formtemplate_default_id', 'template_category_id', 'delete');
/* 2023-02-16-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'languages', 'language_id', (SELECT DATABASE()), 'formtemplates_defaults', 'formtemplate_default_id', 'language_id', 'no-delete');
/* 2023-02-16-4 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'formtemplates_defaults', 'formtemplate_default_id', 'form_category_id', 'no-delete');
/* 2023-02-16-5 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'formtemplates_defaults', 'formtemplate_default_id', 'org_contact_id', 'no-delete');
/* 2023-02-19-1 */	INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Registration', NULL, (SELECT category_id FROM categories c WHERE path = 'event'), 'event/registration', "&alias=event/registration", 5, NOW());
/* 2023-03-03-1 */	ALTER TABLE `usergroups` ADD `organisation_contact_id` int unsigned NULL AFTER `active`;	
/* 2023-03-03-2 */	ALTER TABLE `usergroups` ADD INDEX `organisation_contact_id` (`organisation_contact_id`);
/* 2023-03-03-3 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'contacts', 'contact_id', (SELECT DATABASE()), 'usergroups', 'usergroup_id', 'organisation_contact_id', 'no-delete');
/* 2023-03-04-1 */	ALTER TABLE `registrations` CHANGE `registration_id` `invitation_id` int unsigned NOT NULL AUTO_INCREMENT FIRST, CHANGE `registration_hash` `invitation_hash` varchar(6) COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `show_remaining_from`, RENAME TO `invitations`;
/* 2023-03-04-2 */	UPDATE _relations SET `detail_table` = 'invitations', `detail_id_field` = 'invitation_id' WHERE `detail_db` = (SELECT DATABASE()) AND `detail_table` = 'registrations';
/* 2023-03-04-3 */	UPDATE webpages SET content = REPLACE(content, '%%% forms registration *', '%%% forms invitation *') WHERE content LIKE '%\%\%\% forms registration *%';
/* 2023-04-11-1 */	UPDATE _relations SET master_table = detail_table, master_field = detail_field, detail_table = 'usergroups_categories', detail_id_field = 'uc_id' WHERE master_table = 'usergroups_categories';
/* 2023-04-30-1 */	UPDATE categories SET `parameters` = '&alias=template-types' WHERE `path` = 'template-types' AND ISNULL(parameters);
/* 2023-04-30-2 */	UPDATE categories SET `parameters` = CONCAT(parameters, '&access=login') WHERE `path` = 'template-types/field-changed' AND parameters NOT LIKE '%&access=login%';
/* 2023-05-01-1 */	CREATE TABLE `registrations` (`registration_id` int unsigned NOT NULL AUTO_INCREMENT, `event_id` int unsigned NOT NULL, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`registration_id`), KEY `event_id` (`event_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/* 2023-05-01-2 */	INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'events', 'event_id', (SELECT DATABASE()), 'registrations', 'registration_id', 'event_id', 'no-delete');
